


```{r}
 
# clean memory
rm(list = ls())

#link To file
link='https://github.com/PUBPOL-542/R/raw/main/index.Rmd'

myFile=url(link)

# reading in data:
library(readxl)
multidata =  read_excel("povertyWA.xlsx")


# reset indexes to R format:
row.names(multidata)=NULL
```



```{r}
# hypothesis 1: Poverty is associated with educational attainment level
hypo1=formula(poverty ~ educ)

# hypothesis 2: Poverty is associated with educational attainment level, family size 

hypo2=formula(poverty ~ educ + famsize)

# hypothesis 3: Poverty is associated with educational attainment level, family size, Hours worked per week

hypo3=formula(poverty ~ educ + famsize + uhrswork)

# hypothesis 4: Poverty is associated with educational attainment level, family size, Hours worked per week and Race

hypo4=formula(poverty ~ educ + famsize + uhrswork + race)

# hypothesis 5: Poverty is associated with educational attainment level, family size, Hours worked per week, Race and fluency in English

hypo5=formula(poverty ~ educ + famsize + uhrswork + race + speakeng)

# hypothesis 6: Poverty is associated with educational attainment level, family size, Hours worked per week, Race, fluency in English and energy burden

hypo6=formula(poverty ~ educ + famsize + uhrswork + race + speakeng + energyburden)
```




```{r}
# results
gauss1=glm(hypo1,
           data = multidata,
           family = 'gaussian')

gauss2=glm(hypo2,
           data = multidata,
           family = 'gaussian')

gauss3=glm(hypo3,
           data = multidata,
           family = 'gaussian')
           
gauss4=glm(hypo4,
           data = multidata,
           family = 'gaussian')
          
gauss5=glm(hypo5,
           data = multidata,
           family = 'gaussian')
           
gauss6=glm(hypo6,
           data = multidata,
           family = 'gaussian')
```



```{r}
summary(gauss1)
summary(gauss2)
summary(gauss3)
summary(gauss4)
summary(gauss5)
summary(gauss6)

```
           


```{r}
library(rsq)
rsq(gauss1,adj=T); rsq(gauss2,adj=T); rsq(gauss3,adj=T); rsq(gauss4,adj=T); rsq(gauss5,adj=T); rsq(gauss6,adj=T)
```


           
```{r}
anova(gauss1,gauss2,gauss3,gauss4,gauss5,gauss6,test="Chisq")
```
           
